const DATE_FORMAT = 'DD/MM/YYYY';
const CREATE_USER_PERMISSION = 'criar usuário';
const GET_USER_PERMISSION = 'ler usuário';
const DELETE_USER_PERMISSION = 'remover usuário';
const CREATE_PATIENT_PERMISSION = 'criar paciente';
const GET_PATIENT_PERMISSION = 'ler paciente';
const DELETE_PATIENT_PERMISSION = 'remover paciente';

module.exports = {
  DATE_FORMAT,
  CREATE_USER_PERMISSION,
  GET_USER_PERMISSION,
  DELETE_USER_PERMISSION,
  CREATE_PATIENT_PERMISSION,
  GET_PATIENT_PERMISSION,
  DELETE_PATIENT_PERMISSION,
};
